using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Dama.Core.Common.Helpers;
using Dama.Fin.Domain.Contracts.Service.Report;
using Dama.Fin.Domain.Vm.Budgeting;
using iTextSharp.text;
using iTextSharp.text.pdf;

namespace Dama.Fin.Infrastructure.Reporting.Activity.Outlay
{
    public class OutlayAnalysisReport : IOutlayAnalysisReport
    {
        public async Task<byte[]> GenerateAsync(List<OutlayDashVm> data, BudgetAnalysisOptions options)
        {
            if (data == null)
                throw new InvalidEnumArgumentException(nameof(data));

            if (options == null)
                throw new InvalidEnumArgumentException(nameof(options));

            await using var ms = new MemoryStream();
            var document = new Document(PageSize.A4.Rotate(), 25, 25, 30, 1);
            var writer = PdfWriter.GetInstance(document, ms);
            document.Open();

            var cb = writer.DirectContent;

            document.Add(GetReportHeader(options));
            document.Add(GetReportBody(data));

            WritePageFooter(cb, writer);

            WriteReportMetaInfo(document);

            document.Close();
            writer.Close();

            var reportBytes = ms.ToArray();

            ms.Close();
            return reportBytes;
        }


        private static void WritePageFooter(PdfContentByte cb, PdfWriter writer)
        {
            var bfTimes = BaseFont.CreateFont(BaseFont.TIMES_ROMAN, BaseFont.CP1252, false);

            cb.BeginText();
            cb.SetFontAndSize(bfTimes, 9);

            cb.SetLineWidth(0f);
            cb.MoveTo(30, 40);
            cb.LineTo(815, 40);
            cb.Stroke();

            cb.SetTextMatrix(30, 20);
            cb.ShowText($"Page {writer.PageNumber} of {writer.PageNumber}");

            //cb.SetTextMatrix(400, 20);
            cb.ShowTextAligned(PdfContentByte.ALIGN_CENTER, "Generated by Dama Finance", 407, 20, 0);

            cb.EndText();
        }

        private static Font GetFont(float fontSize, int fontStyle, string fontName = "Tahoma") =>
            FontFactory.GetFont(fontName, fontSize, fontStyle);

        private static PdfPTable GetReportHeader(BudgetAnalysisOptions options)
        {
            var table = new PdfPTable(3)
            {
                WidthPercentage = 100,
                HorizontalAlignment = Element.ALIGN_LEFT
            };

            WriteReportHeader(table, options);

            return table;
        }

        private static void WriteReportHeader(PdfPTable table, BudgetAnalysisOptions options)
        {
            var titleFont = GetFont(13f, 1);
            var subTitleBoldFont = GetFont(10f, 1);
            var subTitleFont = GetFont(10f, 0);
            var emptyRowFont = GetFont(6f, 0);
            var printPeriodFont = GetFont(10f, 0);

            const int maxColumn = 3;

            WriteRow(table, "CAMEROON BAPTIST CONVENTION HEALTH SERVICES", maxColumn, titleFont);
            WriteRow(table, "CDC/PEPFAR HIV FREE PROJECT ZONE I", maxColumn, subTitleFont);
            WriteRow(table, "", maxColumn, emptyRowFont);
            WriteRow(table, $"{options.ReportTitle.ToUpper()}", maxColumn, subTitleBoldFont);
            WriteEmptyRow(table, "", 1, maxColumn, emptyRowFont);
            WriteRow(table, $"PERIOD FROM {options.StartDate.ToShortDateFormat()} - {options.EndDate.ToShortDateFormat()}", maxColumn, printPeriodFont);
            WriteEmptyRow(table, "", 1, maxColumn, emptyRowFont);
            WriteRow(table, $"{options.Region.ToUpper()} REGION", maxColumn, printPeriodFont);
            WriteEmptyRow(table, "", 2, maxColumn, emptyRowFont);
        }

        private static void WriteRow(PdfPTable table, string text, int colSpan, Font font,
            int horizontalAlignment = Element.ALIGN_CENTER, int border = 0, int extraParagraphSpace = 0)
        {
            var cell = new PdfPCell(new Phrase(text, font))
            {
                Colspan = colSpan,
                HorizontalAlignment = horizontalAlignment,
                Border = border,
                ExtraParagraphSpace = extraParagraphSpace
            };
            table.AddCell(cell);
            table.CompleteRow();
        }

        private static void WriteEmptyRow(PdfPTable table, string text, int nCount, int colSpan, Font font,
            int horizontalAlignment = Element.ALIGN_CENTER, int border = 0, int extraParagraphSpace = 0)
        {
            for (var i = 1; i <= nCount; i++)
            {
                var cell = new PdfPCell(new Phrase(text, font))
                {
                    Colspan = colSpan,
                    HorizontalAlignment = horizontalAlignment,
                    Border = border,
                    ExtraParagraphSpace = extraParagraphSpace
                };
                table.AddCell(cell);
                table.CompleteRow();
            }
        }

        private static PdfPTable GetReportBody(List<OutlayDashVm> data)
        {
            var table = new PdfPTable(10)
            {
                WidthPercentage = 100,
                HorizontalAlignment = Element.ALIGN_LEFT
            };

            SetTableColumnWidths(table);

            //table.HeaderRows = 2;

            //Report Header
            WritePageHeader(table);

            var font = GetFont(9f, 0);
            // detail table body
            foreach (var outlayAnalysis in data)
            {
                WriteReportDetail(table, outlayAnalysis.BudgetCode, font, BaseColor.White, Element.ALIGN_LEFT);
                WriteReportDetail(table, outlayAnalysis.Indicator, font, BaseColor.White, Element.ALIGN_LEFT);
                WriteReportDetail(table, outlayAnalysis.AnnualTarget.ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
                WriteReportDetail(table, outlayAnalysis.ComponentTarget.ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
                WriteReportDetail(table, outlayAnalysis.PeriodTarget.ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
                WriteReportDetail(table, outlayAnalysis.PeriodAchievement.ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
                WriteReportDetail(table, outlayAnalysis.PercentageAchievement.ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
                WriteReportDetail(table, outlayAnalysis.ComponentBudget.ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
                WriteReportDetail(table, outlayAnalysis.PeriodExpenditure.ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
                WriteReportDetail(table, outlayAnalysis.PercentageExpenditure.ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
            }

            //Report Totals
            WriteReportFooter(table, data);

            return table;
        }

        private static void WriteReportFooter(PdfPTable table, IReadOnlyCollection<OutlayDashVm> data)
        {
            var font = GetFont(9f, 0);

            WriteReportDetail(table, "", font, BaseColor.White);
            WriteReportDetail(table, "TOTAL", font, BaseColor.White, Element.ALIGN_LEFT);
            WriteReportDetail(table, data.Sum(x => x.AnnualTarget).ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
            WriteReportDetail(table, data.Sum(x => x.ComponentTarget).ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
            WriteReportDetail(table, data.Sum(x => x.PeriodTarget).ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
            WriteReportDetail(table, data.Sum(x => x.PeriodAchievement).ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
            WriteReportDetail(table, data.Sum(x => x.PercentageAchievement).ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
            WriteReportDetail(table, data.Sum(x => x.ComponentBudget).ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
            WriteReportDetail(table, data.Sum(x => x.PeriodExpenditure).ToString("##,##0"), font, BaseColor.White, Element.ALIGN_RIGHT);
            WriteReportDetail(table, data.Sum(x => x.PercentageExpenditure).ToString("##,##0"), font, BaseColor.White,
                Element.ALIGN_RIGHT);
        }

        private static void WriteReportMetaInfo(Document document)
        {
            var table = new PdfPTable(5)
            {
                WidthPercentage = 100,
                HorizontalAlignment = Element.ALIGN_LEFT,
                
            };

            document.Add(new Phrase("\n"));

            AddColumn(table, "Expected weekly target");
            AddColumn(table, "100%");
            AddColumn(table, "");
            AddColumn(table, "Expected weekly expenditure");
            AddColumn(table, "0%");

            AddColumn(table, "Acutal Target met for the next week");
            AddColumn(table, "100%");
            AddColumn(table, "");
            AddColumn(table, "Acutal Weekly expenditure");
            AddColumn(table, "0%");


            AddColumn(table, "%tage of target still to be met");
            AddColumn(table, "100%");
            AddColumn(table, "");
            AddColumn(table, "%tage of weekly expenditure still to be met");
            AddColumn(table, "0%");

            document.Add(table);
        }

        private static void AddColumn(PdfPTable table, string text, int size = 1)
        {
            var font = GetFont(10f, 0);
            var cell = new PdfPCell(new Phrase(text, font))
            {
                Rowspan = size
            };

            table.AddCell(cell);
        }

        private static void WritePageHeader(PdfPTable table)
        {
            var font = GetFont(9f, 0);

            WriteReportDetail(table, "BUDGET CODE", font, BaseColor.Gray);
            WriteReportDetail(table, "INDICATOR", font, BaseColor.Gray);
            WriteReportDetail(table, "ANN TGT", font, BaseColor.Gray);
            WriteReportDetail(table, "COMP TARGET", font, BaseColor.Gray);
            WriteReportDetail(table, "WEEKLY TGT", font, BaseColor.Gray);
            WriteReportDetail(table, "ACHEIVEMENT", font, BaseColor.Gray);
            WriteReportDetail(table, "% ACHIEVED", font, BaseColor.Gray);
            WriteReportDetail(table, "COMP BGT", font, BaseColor.Gray);
            WriteReportDetail(table, "EXPEND", font, BaseColor.Gray);
            WriteReportDetail(table, "% EXPEND", font, BaseColor.Gray);

            table.CompleteRow();
        }

        private static void WriteReportDetail(PdfPTable table, string text, Font font, BaseColor backgroundColor,
            int horizontalAlignment = Element.ALIGN_CENTER, int verticalAlignment = Element.ALIGN_MIDDLE)
        {
            var cell = new PdfPCell(new Phrase(text, font))
            {
                HorizontalAlignment = horizontalAlignment,
                VerticalAlignment = verticalAlignment,
                BackgroundColor = backgroundColor,
                Padding = 4,
                NoWrap = true,
                UseBorderPadding = true
            };
            table.AddCell(cell);
        }

        private static void SetTableColumnWidths(PdfPTable table)
        {
            var sizes = new float[10];
            const int w = 30;
            for (var i = 0; i < 10; i++)
            {
                sizes[i] = i switch
                {
                    0 => 60,
                    1 => 80,
                    2 => w,
                    3 => w,
                    4 => w,
                    5 => w,
                    6 => w,
                    7 => w,
                    8 => w,
                    9 => w,
                    _ => sizes[i]
                };
            }

            table.SetWidths(sizes);
        }

        
    }

}
